site_name: 4500 Documentation

theme:
  name: material
  logo: assets/logo_transparent.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-1
        name: Switch to dark mode
      primary: indigo
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/brightness-5
        name: Switch to light mode    
      primary: deep purple
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FRCTeam4500
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/team4500/
    - icon: material/view-gallery-outline
      link: https://www.robohounds.com/

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/FRCTeam4500"  target="_blank" rel="noopener">FRC Team 4500</a>