site_name: 4500 Documentation

theme:
  name: material
  logo: assets/logo_transparent.svg
  favicon: assets/logo_noblue.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    # - toc.integrate
    - toc.follow
    - navigation.top
    - pdf-export
    - search.suggest
    - footnotes
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/brightness-5
        name: Switch to light mode    
      primary: deep purple
      accent: orange

extra:
  generator: false
  homepage: https://frcteam4500.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FRCTeam4500
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/team4500/
    - icon: material/view-gallery-outline
      link: https://www.robohounds.com/

repo_url: https://www.github.com/FRCTeam4500/mkdocs-4500-docs
repo_name: mkdocs-4500-docs

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - toc:
      title: On this page
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.arithmatex:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - offline:
      enabled: !ENV [OFFLINE, false]

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/FRCTeam4500"  target="_blank" rel="noopener">FRC Team 4500</a>